### ISSUE TITLE
Error when try run main.py

### ISSUE THREAD

**Issue by felansu** [mckinziebrandon/DeepChatModels#4]
> **python main.py**
```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    import data
  File "c:\Repositories\DeepChatModels\data\__init__.py", line 2, in <module>
    from data._dataset import Dataset
  File "c:\Repositories\DeepChatModels\data\_dataset.py", line 5, in <module>
    from utils import io_utils
  File "c:\Repositories\DeepChatModels\utils\__init__.py", line 1, in <module>
    from utils import io_utils
  File "c:\Repositories\DeepChatModels\utils\io_utils.py", line 18, in <module>
    from chatbot.globals import DEFAULT_FULL_CONFIG
  File "c:\Repositories\DeepChatModels\chatbot\__init__.py", line 2, in <module>
    from chatbot.components.base._rnn import  *
  File "c:\Repositories\DeepChatModels\chatbot\components\__init__.py", line 3, in <module>
    from chatbot.components.encoders import BasicEncoder, UniEncoder, BidirectionalEncoder
  File "c:\Repositories\DeepChatModels\chatbot\components\encoders.py", line 4, in <module>
    from tensorflow.contrib.rnn import GRUCell
ImportError: cannot import name 'GRUCell'
```
**Tested with**
* Tensorflow: 0.12.0-rc1 | 0.12.1 | 1.0.1 | 1.0.0
* Python: 3.5.3

**Comment by mckinziebrandon** [comment]
That is a rather unexpected error, since that import should work for all tensorflow versions you listed. I'll look into this further. In the meantime, as a sanity check, could you just try running the following in a python session:

```python
import tensorflow as tf
from tensorflow.contrib.rnn import GRUCell
```

Thanks!

**Comment by felansu** [comment]
Oh... sorry @mckinziebrandon, 
i'm forget run `python setup.py install` command...
Thanks !
